apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: tickets
          env:
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            # k create secret generic jwt-secret --from-literal=JWT_KEY=asdf command to create a SECRET object
            # name thats going to be used INSIDE the container
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  # --from-literal part
                  key: JWT_KEY
                  # the name that we used
                  name: jwt-secret
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
      name: tickets
      protocol: TCP
